# for my itproject web application
# install apache and import the application from the git repo
# jsanjuan - 06/14/2019

FROM ubuntu:18.04

ENV TZ=Asia/Singapore
ARG EXTERNAL_IP

# configure timezone so it does not prompt during install, apache and clone it project from git repo
RUN apt-get update && \
    /bin/ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone  && \
    apt-get -y install apache2 apache2-bin php php-pgsql git  && \
    /bin/sed -i 's+/var/www/html+/var/www/html/it-project/www+g' /etc/apache2/sites-available/000-default.conf   && \
    cd /var/www/html  && \
    /usr/bin/git clone https://jsanjuansg@bitbucket.org/jsanjuansg/it-project.git


# configure it project application with external IP
RUN /bin/echo $EXTERNAL_IP > /tmp/ip.txt  && \
    /bin/echo "/bin/sed -i 's+\$itproject_url = \"x\"+\$itproject_url = \"$(/bin/cat /tmp/ip.txt)\"+g' /var/www/html/it-project/www/itproject.php"  > /tmp/rp.txt  && \
    /bin/sh /tmp/rp.txt  && \
    /bin/rm -f /tmp/rp.txt /tmp/ip.txt 

# Make port 80 available to the world outside this container
EXPOSE 80

CMD /usr/sbin/apache2ctl -DFOREGROUND

