# for my itproject web application
# install apache web and postgresql servers (details in the respective dockerfiles)
# jsanjuan - 06/14/2019

version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-web
      args:
        - EXTERNAL_IP=192.168.88.18
    image: itproject-apache2:1.2
    ports:
      - 80:80

  pgsql:
    build: 
      context: .
      dockerfile: Dockerfile-db
    image:  itproject-pgsql:1.0
