# for my itproject web application
# install apache and needed modules/tools and import the application from the git repo
# jsanjuan - 06/13/2019

FROM debian:9

ARG EXTERNAL_IP

RUN apt-get update && \
    apt-get -y install apache2 apache2-bin php php-mysql git redis-tools php-redis && \
    /bin/sed -i 's+/var/www/html+/var/www/html/it-project/www+g' /etc/apache2/sites-available/000-default.conf   && \
    cd /var/www/html  && \
    /usr/bin/git clone -b mysql-redis https://jsanjuansg@bitbucket.org/jsanjuansg/it-project.git


RUN /bin/echo $EXTERNAL_IP > /tmp/ip.txt  && \
    /bin/echo "/bin/sed -i 's+\$itproject_url = \"x\"+\$itproject_url = \"$(/bin/cat /tmp/ip.txt)\"+g' /var/www/html/it-project/www/itproject.php"  > /tmp/rp.txt  && \
    /bin/sh /tmp/rp.txt  && \
    /bin/rm -f /tmp/rp.txt /tmp/ip.txt 

# Make port 80 available to the world outside this container
EXPOSE 80

CMD /usr/sbin/apache2ctl -DFOREGROUND

