# for my itproject web application
# install mariadb and import the db schema from the git repo
# jsanjuan - 06/08/2019

FROM debian:9

RUN apt-get update && \
    apt-get -y install mariadb-server mariadb-client git

# Copy itproject/ contents into the container at /tmp/
#COPY itproject/ /tmp/

# Configure MariaDB to listen on all IP addresses and not just localhost
RUN /bin/sed -i 's/127.0.0.1/*/gI' /etc/mysql/mariadb.conf.d/50-server.cnf

RUN /etc/init.d/mysql start  &&  \
    /bin/sleep 5 && \
    cd /tmp && \
    /usr/bin/git clone -b mysql-redis https://jsanjuansg@bitbucket.org/jsanjuansg/it-project.git  && \
    /usr/bin/mysql -u root -e "create database itproject"  && \
    /usr/bin/mysql -u root < /tmp/it-project/db/itproject.sql  && \
    /usr/bin/mysql -u root -e "CREATE USER 'itproject'@'%' IDENTIFIED BY 'Db#sap1434'"  && \
    /usr/bin/mysql -u root -e "GRANT ALL PRIVILEGES ON itproject.* TO 'itproject'@'%'"  && \
    /etc/init.d/mysql stop  && \
    /bin/rm -rf /tmp/it-project

# Make port 3306 available to the world outside this container
#EXPOSE 3306

CMD /usr/bin/mysqld_safe

