# for my itproject web application
# install apache web and mariadb servers (details in the respective dockerfiles)
# jsanjuan - 06/08/2019

version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-web
      args:
        - EXTERNAL_IP=192.168.88.18
    image: itproject-web:1.0
    ports:
      - 80:80
        #    volumes:
        #      - /home/joshua/my-docker-app/itproject:/var/www/html/itproject

  mariadb:
    build: 
      context: .
      dockerfile: Dockerfile-db
    image:  itproject-mariadb:1.0
